blank_issues_enabled: false
contact_links:
  - name: Join the Discussion
    url: https://github.com/nicole-obrien/demo-open-source-repo/discussions
    about: Request features, leave feedback or discuss ideas
