blank_issues_enabled: false
contact_links:
  - name: Join the Discussion
    url: /discussions
    about: Request features, leave feedback or discuss ideas
  - name: Report a Vulnerability
    url: /security/policy
    about: Please read our security policy to find out how to report a vulnerability
